### PR TITLE
Apply Example_ynh

### LINKED ISSUE #15: Data folder should be in yunohost.app
The data folder should be in /home/yunohost.app/funkwhale/data because sometimes the media can take lot of space fill up the limited space in /var. /home folder is generally reserved with lot of space to keep all the media. Further its good idea to keep media away from the app core files.
 I have faced this issue in Peertube too. 
See here https://github.com/YunoHost-Apps/peertube_ynh/issues/8

### PR DESCRIPTION
**Pull request by yalh76**
## Solution
- *Apply Example_ynh*
- *Fix #15*
- *Fix security issue*
- *Stick to official documentation installation*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Package_check results
---
* An automatic package_check will be launch at https://ci-apps-dev.yunohost.org/, when you add a specific comment to your Pull Request: "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!"*

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
I know it's a bit huge to review but seems necessary ^^

**Review by ericgaspar — APPROVED** [review]
Wow! Big rework. LGTM

**Comment by yalh76** [comment]
!testme

**Review by Sporiff — APPROVED** [review]
This looks fantastic. I particularly like the addition of the migration during upgrade (I'd had a go at that myself a little while ago and couldn't really get my head around it). If this has been tested in install, upgrade, remove, and restore conditions I'm more than happy to merge.

**Comment by Thovi98** [comment]
I’ve just tested 

✔️  an upgrade from actual 1.1 master on a test instance to 1.1.1 example
✔️ remove of the new 1.1.1 example
✔️ restore of the backup

Everything’s fine, thank you so much @yalh76 🥳

**Pull request merged**
