### PR TITLE
Use released 0.17

### PR DESCRIPTION
**Pull request by rushsteve1**
Bumped up to the released 0.17
Also turned on LDAP. I think I got the settings right but please correct me if I didn't.

Feedback welcome! There is likely some issues with the upgrade to 0.17. but LDAP support is worth it.

### CODE REVIEW

**Comment by EliotBerriot** [comment]
Don't forget there is a script to run for this upgrade: https://docs.funkwhale.audio/upgrading/0.17.html#upgrade-instructions

**Comment by rushsteve1** [comment]
Looks like the script was already added to the upgrade file by commit 331300c6a9a0fc86d1767d3cbe39b8841f2449bf

**Comment by EliotBerriot** [comment]
Awesome, I missed that!

**Comment by Jibec** [comment]
thanks for your help, I'm afraid you LDAP connection didn't work, it is now fixed with this commit: https://github.com/YunoHost-Apps/funkwhale_ynh/commit/3e44180708dddbef360e25841b9cf7be6e144c95

**Comment by anmol26s** [comment]
Great going to test it.
But Ldap without fail2ban or 2 factor authentication is risky.

**Comment by rushsteve1** [comment]
@anmol26s YunoHost itself runs Fail2Ban

**Comment by anmol26s** [comment]
Yes but it needs to be integrated to the apps.

**Comment by Jibec** [comment]
Ah? Good to know, thanks. Do you have an example of fail2ban usage and ideal ynh documentation? We have many apps with LDAP and no fail2ban support.

Please open an issue to keep track of this.

**Comment by anmol26s** [comment]
I did it for shaarli app : 
This is the helper
https://github.com/YunoHost-Apps/shaarli_ynh/blob/testing/scripts/_common.sh#L16-L78

Fail2ban checks logs for failed attempts and block rules have to be set.Maybe @EliotBerriot can create separate log file for the authentication.
Command : 
https://github.com/YunoHost-Apps/shaarli_ynh/blob/testing/scripts/install#L136

**Comment by Jibec** [comment]
OK, but please don't continue the conversation here, it should continue in this issue: https://github.com/YunoHost-Apps/funkwhale_ynh/issues/47

**Pull request closed without merging**
