### PR TITLE
Funkwhale 1.2.8 upgrade

### PR DESCRIPTION
**Pull request by yalh76**
## Problem

- A new bugfix release came out that fixes issues with pyopenssl and cryptography

## Solution

- Bump the version from 1.2.7 to 1.2.8

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by Thovi98** [comment]
As some upgrade test fail because the initial Funkwhale version cannot be installed, should we remove those test?
Upgrade seems okay for existing installations.

**Comment by yalh76** [comment]
> As some upgrade test fail because the initial Funkwhale version cannot be installed, should we remove those test? Upgrade seems okay for existing installations.

Yes we can remove not working tests

**Comment by yalh76** [comment]
!testme

**Pull request merged**
