### PR TITLE
Using yunohost.multimedia

### PR DESCRIPTION
**Pull request by Aeris1One**
Using /home/yunohost.multimedia/share/Music instead of default.

### CODE REVIEW

**Comment by Aeris1One** [comment]
I don't know if it's the best way... Maybe I'm wrong... The docs are weird...

**Comment by Aeris1One** [comment]
Another way would be a Cron job which run in-place import command from the directory every day.

**Comment by Jibec** [comment]
Thanks for your help. Where is the doc you refers to?
With the current status of your PR, I'm afraid we could have conflicts 
if we install multiple version of Funkwhale on the same server.

**Comment by Aeris1One** [comment]
Well... The best way would be to keep actual directory (finalpath/import/) and symlink yunohost's directory into. Then, everyday, runs the in-place import command from finalpath/import/.

**Pull request closed without merging**
