### PR TITLE
Translate packages.json strings to French

### PR DESCRIPTION
**Pull request by JocelynDelalande**

### CODE REVIEW

**Comment by Jibec** [comment]
Thanks for your contribution, but we now use our translation platform for this: https://translate.yunohost.org

I do prefer to encourage this way of translating rather than Github, it makes translator life way easier.
I hope you understand! There is always stuff to translate :)

**Comment by JocelynDelalande** [comment]
Yeah, no prob, that wasn't hours of work anyway.

**Comment by zicmama** [comment]
How to install and acivate french translation?

**Comment by Jibec** [comment]
you'll be able to upgrade your package soon, thanks to https://github.com/YunoHost-Apps/funkwhale_ynh/pull/28

**Pull request closed without merging**
