### PR TITLE
Update about the 1.3.3 release

### PR DESCRIPTION
**Pull request by stilobique**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Thovi98** [comment]
!testme

**Comment by Thovi98** [comment]
Thank you!
For your information, there is no need to change te Readme(s).md as they will be updated automatically once merged :)
Thanks anyway, greatly appreciated!

**Comment by stilobique** [comment]
Ho, alright.

**Comment by Thovi98** [comment]
Thanks for your successful work 🎉

**Comment by Thovi98** [comment]
(And for the future, we first need to merge in the testing branch, and then in master 😇).

**Pull request merged**
