### PR TITLE
Change url

### PR DESCRIPTION
**Pull request by Thovi98**
Thanks @ericgaspar for bringing `change_url` here !!
I make this PR to comment it after testing : 

The url change in itself works great ! I successed change from `music.domain.nohost.me` to `test.domain.nohost.me`.

But Funkwhale has federation, and when I check the users of the instance, there federation name doesn’t change.
e.g. : music.domain.nohost.me (user: thomas@music.domain.nohost.me) --> `change_url` --> test.domain.nohost.me (user: thomas@music.domain.nohost.me (didn’t change)). So if I want to go on this profile, I come on the Yunohost tiles page, because music.domain.nohost.me has no app anymore. Same if I had created a channel on the first url. 

I don’t know how if it’s clear, nor how to improve this, but I hope that my testing help.

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
@Thovi98 
`change_url` The script now regenerates the configuration file. That it changes the federation name?

**Comment by Thovi98** [comment]
> That it changes the federation name?

I’ve just tried, and no it didn’t change unfortunately... It has the same behavior as explained.

**Comment by ericgaspar** [comment]
@Thovi98 Do you mind testing my changes. Does the address of the federation change?

**Comment by Thovi98** [comment]
I’ve just tested, and unfortunately it’s still the same.

**Comment by ericgaspar** [comment]
Damn ... Can you describe your steps on how you check the address federation changes, (practically what page / settings are you looking at) ?

**Comment by Thovi98** [comment]
Yes of course !
Once the app is installed on `music.domain.tld`, log in and go to your profile page : `music.domain.tld/@thomas/`
As an admin user, you also can go to settings --> users --> click on thomas (the page you arrive at is `music.domain.tld/manage/moderation/accounts/thomas@music.domain.tld`)

After changing url to `test.domain.tld`:
Go to your profile page. Experiment that it loads forever. 
Instead of that, go to settings --> users --> click on thomas (the page you arrive at is `https://test.domain.tld/manage/moderation/accounts/thomas@music.domain.tld`)

From that last window, clicking on `open profile`, a new window will appear with the url `https://test.domain.tld/federation/actors/thomas` and the message `server error (500)`

I hope my post answers to what you asked. And I hope it helps !
Thanks !

**Comment by Thovi98** [comment]
I don’t know if you already took a look at the [official documentation](https://docs.funkwhale.audio/admin/url.html#on-non-docker-installations) for changing url ? 

There is a command to change all mentions of the old instance URL in the database:
`python manage.py fix_federation_ids https://old-url https://new-url --no-dry-run --no-input` 
I didn’t find this command in the `change_url` script. I don’t know if that helps.

**Comment by ericgaspar** [comment]
this line mentioned on the doc is line 134 in the `change_url` script...

**Comment by Thovi98** [comment]
Okay, it’s not really supported because of the federation... 
But someone has similar issue as our, the database has to be modified.
https://dev.funkwhale.audio/funkwhale/funkwhale/-/issues/1393

I don’t know if it’s a good idea to continue trying this since it’s not really supported upstream.

**Comment by yalh76** [comment]
Switched to #146

**Pull request closed without merging**
