### PR TITLE
WIP: Update 0.18

### PR DESCRIPTION
**Pull request by PierrickBrun**
To address #56 

For now, it installs itself but package_check gets 502 errors when trying to connect to the app.

### CODE REVIEW

**Comment by Jibec** [comment]
Hint: don't use the "include" directive, report default configuration in the nginx file.

**Comment by EliotBerriot** [comment]
> For now, it installs itself but package_check gets 502 errors when trying to connect to the app.

It likely indicates that the `funkwhale-server` service is not running. If you want to share the logs for this process, I can have a look :)

**Comment by PierrickBrun** [comment]
Okay nevermind, the `/var/log/funkwhale/server.log` is empty so I guess the requests weren't hitting it.

Voici le résultat de `service funkwhale-server status`:
`Jan 28 18:03:22 pchecker_lxc systemd[1]: Started Funkwhale (funkwhale) application server.
Jan 28 18:03:24 pchecker_lxc funkwhale-server[9298]: 2019-01-28 18:03:24,795 INFO     Loaded env file at /var/www/funkwhale/code/config/.env
Jan 28 18:03:26 pchecker_lxc funkwhale-server[9298]: 2019-01-28 18:03:26,654 INFO     Starting server at tcp:port=5000:interface=127.0.0.1
Jan 28 18:03:26 pchecker_lxc funkwhale-server[9298]: 2019-01-28 18:03:26,665 INFO     HTTP/2 support not enabled (install the http2 and tls Twisted extras)
Jan 28 18:03:26 pchecker_lxc funkwhale-server[9298]: 2019-01-28 18:03:26,665 INFO     Configuring endpoint tcp:port=5000:interface=127.0.0.1
Jan 28 18:03:26 pchecker_lxc funkwhale-server[9298]: 2019-01-28 18:03:26,671 INFO     Listening on TCP address 127.0.0.1:5000`

I wonder if this Pillow version warning is causing trouble, any idea @EliotBerriot ?
http2 isn't activated in the nginx conf so this shouldn't come from this https://dev.funkwhale.audio/funkwhale/funkwhale/commit/635865ac82e2a3ff3641c22e45d95587b95bc149 .

**Comment by EliotBerriot** [comment]
@PierrickBrun I don't see any Pillow warning in your logs, sorry (and the HTTP2 thing can be safely ignored) :)

**Comment by Jibec** [comment]
I'm working on this, the way to make it work is to take line by line the new nginx template and adapt it with YunoHost specifics: https://dev.funkwhale.audio/funkwhale/funkwhale/blob/0.18.1/deploy/nginx.template

but once done, we stil have an issue:
`requests.exceptions.SSLError: HTTPSConnectionPool(host='ff.jb9.fr', port=443): Max retries exceeded with url: /front/index.html (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)'),))`

the API calls the server, nginx force it to be https and django cries because it's a selfsign certificate and it crashes.

Eliot said he would help to fix this.

**Comment by PierrickBrun** [comment]
Thank you, I had a bit of trouble getting this to work :)

Le 08/02/2019 à 17:24, Jean-Baptiste a écrit :

**Comment by Jibec** [comment]
I couldn't guess it was so hard sorry! Eliot did change a lot of the hosting logic of his creation ;)

**Comment by EliotBerriot** [comment]
Hi there, sorry for the issue!

[I've published a fix](https://dev.funkwhale.audio/funkwhale/funkwhale/merge_requests/592) for that yesterday, and if you use [this commit](https://dev.funkwhale.audio/funkwhale/funkwhale/commit/f780fa24c14d340d93349deb03ec9ccd2669e63d) you can now specify the env var `FUNKWHALE_SPA_HTML_ROOT=/srv/funkwhale/front/dist/index.html` to bypass this network request completely.

Replace `/srv/funkwhale/front/dist/index.html` by the actual path of the front-end `index.html` file with the Yunohost setup :)

**Comment by Jibec** [comment]
looks like fixed upstream, https://docs.funkwhale.audio/changelog.html#id1, I'll try this soon
Note to @EliotBerriot : the anchors are "id1" "id2", "id3", meaning we can't make semi-permanent link as for each release, the correct will change

**Comment by EliotBerriot** [comment]
@Jibec yeah that's a limitation of our current documentation system :s

**Comment by Jibec** [comment]
it should be ready to test, please provide feedback :+1:

**Comment by Jibec** [comment]
@EliotBerriot I'm merging this now, please test and confirm it works fine for you

**Pull request merged**
