### PR TITLE
Cryptography

### LINKED ISSUE #164: Upgrade/install fail on arm architecture
### Describe the bug

App upgrade fail on arm.

### Context

- Hardware: BanaPi R2, (Armv7)
- YunoHost version: 4.3.6
- Previous app version: 1.1.4~ynh1

### Steps to reproduce

On arm board do:
    ```sh
    sudo yunohost app upgrade funkwhale
    ```

### Expected behavior

App upgrade should success but it fail.

### Logs

https://paste.yunohost.org/aqipezezet.bash

### PR DESCRIPTION
**Pull request by Thovi98**
## Problem

- *Description of why you made this PR*

First try to integrate ARM
fixes #164 

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Thovi98** [comment]
!testme

**Comment by Thovi98** [comment]
@rosbeef could you please try this with 

`sudo yunohost app install https://github.com/YunoHost-Apps/funkwhale_ynh/tree/cryptography --debug`
And report back?

Thanks

**Comment by Thovi98** [comment]
Yeaahh thank you for the update!
Could you please share me your logs so I can see?

**Comment by stilobique** [comment]
[Of course, the install log](https://paste.yunohost.org/raw/uveludicik).

**Comment by stilobique** [comment]
My raspberry is only to test, but I don't use a funkwhale. I can look to install the actual version.

**Comment by rosbeef** [comment]
It was not working for me before. And then now it works( at least install finish and I can go to the main page asking for login)
As it needs rustup (armhf always need rustup because of rustc not exist for 32 bits as I understand)

Install logs : https://paste.yunohost.org/raw/izapewayaj

**Comment by Thovi98** [comment]
Yeaaah good news!
Thanks both for testing 🎉

I see in @rosbeef’s logs that the changes here have been taken into account, and not for @stilobique for whom the installation worked already so I consider this solved, thanks!

**Comment by nicofrand** [comment]
> @nicofrand sorry I forgot to ping you about cryptography, but this seems to work for Funkwhale

What's the rationale behind the use of "minimal"?

I went this way in Kresus: https://github.com/YunoHost-Apps/kresus_ynh/blob/tryRaspi4fix/scripts/install#L139-L145

**Pull request merged**
