### PR TITLE
Upgrade to 1.2.4

### PR DESCRIPTION
**Pull request by Thovi98**
## Problem

- New version

## Solution

- Upgrade

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by Thovi98** [comment]
@ericgaspar Thanks ! 
Can I ask you how does auto-readme works ? I thought it would automatically be created by the bot ?

**Comment by yalh76** [comment]
> Can I ask you how does auto-readme works ? I thought it would automatically be created by the bot ?

The bot only works on branches of the repository of https://github.com/YunoHost-Apps

Your branch is in https://github.com/Thovi98

The bot will do its job when your PR will be merged in https://github.com/YunoHost-Apps/funkwhale_ynh/tree/testing

**Comment by Thovi98** [comment]
> The bot only works on branches of the repository of https://github.com/YunoHost-Apps

Oh yes of course, thanks for the explanation !

**Pull request merged**
