### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by renaudponcelet**
This changes solves my issue "channels-redis and python #78"

### CODE REVIEW

**Comment by Jibec** [comment]
Thank you for the reminder, sorry for not responding.

As continuous tests says everything is fine and my own server now hiting 
this bug, I'm waiting for another user to react on the issue.

When I look to Debian packages, the version number 3.6 doesn't looks 
like to be a standard value either for Stretch or Buster:
https://packages.debian.org/search?searchon=names&keywords=python3

So, for now, I'm happy that renaudponcelet found the solution to his 
issue, but won't merge it yet.
By the way, this PR is on the master branch, while it should be in 
testing.

**Comment by alexAubin** [comment]
Well uh note that another user reported this issue on the chat a few days ago, and today an other user encountered it on the forum : https://forum.yunohost.org/t/erreur-a-linstallation-de-funkwhale/8875

**Comment by Jibec** [comment]
OK, then it's a confirmed bug, thank you again :p
Let's see first if that is an upstream one with Eliot, I'll ping him.

**Comment by rakeendo** [comment]
Hello , for your information,  i have the same issue on my yunohost instance.

**Comment by rakeendo** [comment]
Unfortunately, the fix doesn't work for me :/

see the log below:
`Attention : [DEBUG]: DEBUG   - + local username
Attention : [DEBUG]: DEBUG   - + local home_dir
Attention : [DEBUG]: DEBUG   - + local use_shell
Attention : [DEBUG]: DEBUG   - + ynh_handle_getopts_args --username=funkwhale --home_dir=/var/www/funkwhale
Attention : [DEBUG]: DEBUG   - + set +x
Attention : [DEBUG]: DEBUG   - + use_shell=0
Attention : [DEBUG]: DEBUG   - + home_dir=/var/www/funkwhale
Attention : [DEBUG]: DEBUG   - + ynh_system_user_exists funkwhale
Attention : [DEBUG]: DEBUG   - + local legacy_args=u
Attention : [DEBUG]: DEBUG   -=username=)
Attention : [DEBUG]: DEBUG   - + declare -Ar args_array
Attention : [DEBUG]: DEBUG   - + local username
Attention : [DEBUG]: DEBUG   - + ynh_handle_getopts_args funkwhale
Attention : [DEBUG]: DEBUG   - + set +x
Attention : [DEBUG]: DEBUG   - + echo '! Helper used in legacy mode !'
Attention : [DEBUG]: DEBUG   - + set +x
Attention : [DEBUG]: DEBUG   - + getent passwd funkwhale
Attention : [DEBUG]: DEBUG   -'
Attention : [DEBUG]: DEBUG   - + local 'user_home_dir=-d /var/www/funkwhale'
Attention : [DEBUG]: DEBUG   -'
Attention : [DEBUG]: DEBUG   - + local 'shell=--shell /usr/sbin/nologin'
Attention : [DEBUG]: DEBUG   - + useradd -d /var/www/funkwhale --system --user-group funkwhale --shell /usr/sbin/nologin
Attention : [DEBUG]: DEBUG   - + virtualenv -p python3.6 /var/www/funkwhale/code/virtualenv
Attention : [DEBUG]: DEBUG   - **The path python3.6 (from --python=python3.6) does not exist**
Attention : [DEBUG]: DEBUG   - + ynh_exit_properly
Attention : 
Info : L’opération 'Installer l’application 'funkwhale'' a échouée ! Pour avoir de l’aide, merci de partager le journal historisé de cette opération en utilisant la commande 'yunohost log display 20190828-191033-app_install-funkwhale --share'
Info : Loading installation settings...
Info : Stopping and removing the systemd service
Attention : Failed to stop funkwhale-beat.service: Unit funkwhale-beat.service not loaded.`

**Comment by Jibec** [comment]
Please give a try to https://github.com/YunoHost-Apps/funkwhale_ynh/pull/80

**Comment by rakeendo** [comment]
It works !! thank you so much !!

**Pull request closed without merging**
