### PR TITLE
Auto updater

### PR DESCRIPTION
**Pull request by Thovi98**
## Problem

- Cumbersome to update the package

## Solution

- Add auto-updater
/!\ It’s my first time touching at such a github file, so I may have done mistakes... I don’t understand everything 😅

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Review by yalh76 — APPROVED** [review]
Didn't test it but I trust you

**Comment by Thovi98** [comment]
Oh, I didn’t know we could test it, could you explain how before we merge please ?

**Comment by yalh76** [comment]
to test autoupdater, usually I clone the repo, go in the directory and then execute `chmod +x .github/workflows/updater.sh && .github/workflows/updater.sh`
It would update the `manifest.json`, `api.src` and `front.src`

Or we merge into testing and in master, launch an auto upgrade. It will create a new PR and we will see if it's ok or not ...

**Comment by Thovi98** [comment]
Hmmm it doesn’t work.
I manage to find the latest release and to update the manifest, but I’ve no clue how to update `api.src` and `front.src`...
Output is always: `0 available asset(s)`

Maybe it’s because I reach a Gitlab instance? Do I have to put secret tokens?

**Pull request closed without merging**
